### PR TITLE
add: build-vm command to os subcommand

### PR DESCRIPTION
**Pull request by xiro-codes**
Implements build-vm command into nh

### CODE REVIEW

**Comment by viperML** [comment]
Couldn't this be retrofitted into OsRebuildArgs::rebuild instead?

**Comment by xiro-codes** [comment]
Ill look into it, also love you blog it really helped me get into nix early on.

**Comment by viperML** [comment]
So what do you want to do with this command? It is named `build-vm`, but it actually runs the vm. Also it shouldn't install it into the system profile, and probably neither ask for confirmation or diff.

**Comment by xiro-codes** [comment]
I needed to test my config that was broken. so i added it didn't think much farther than that.
ps. it was still broken but its fixed now

**Pull request closed without merging**
