### PR TITLE
add profile naming functionality

### PR DESCRIPTION
**Pull request by GuterBenutzername**
Adds the ability to name profiles, a la nixos-rebuild --profile-name

Quick, dirty, but functional; cleanup is appreciated.

### CODE REVIEW

**Comment by GuterBenutzername** [comment]
for naming profiles when added to the bootloader, for if you prefer to be able to have readable names on boot instead of "Generation 53", "Generation 54", etc.
nixos-rebuild had this feature, so I just reimplemented it here.

**Comment by viperML** [comment]
Doesn't system.nixos.tags already give you some customizability?

**Comment by GuterBenutzername** [comment]
Yes, but it's useful to have the option, particularly in my usage scenario where it's easier to name profiles after the changes that were made compared to the last one (like a git commit message)

**Comment by viperML** [comment]
It doesn't work with systemd-boot.

**Pull request closed without merging**
